# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pipeline_showcase.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import QLabel, QVBoxLayout, QWidget, QPushButton, QApplication
import os
from PyQt5.QtGui import QPixmap
import sys
from os.path import dirname, realpath, join
from PyQt5.QtWidgets import QWidget
from PyQt5.uic import loadUiType
import pandas as pd
from PyQt5 import QtWidgets

from PyQt5_Splash_Screen import SplashScreen

# Define app as a global variable so that we can access it while being redirected from the main.py file
app = QtWidgets.QApplication([])

scriptDir = dirname(realpath(__file__))
From_Main, _ = loadUiType(join(dirname(__file__), "pipeline_showcase.ui"))

class Ui_pipeline(QWidget, From_Main):
    pipeline = None  # Define pipeline as a class attribute so that we can access it while being redirected from the main.py file
    def setupUi(self, pipeline):
        Ui_pipeline.pipeline = pipeline  # Assign pipeline to the class attribute
        pipeline.setObjectName("pipeline")
        pipeline.resize(1200, 800)
        self.pipelineLabel = QtWidgets.QLabel(pipeline)
        self.pipelineLabel.setGeometry(QtCore.QRect(110, 30, 1011, 611))
        self.pipelineLabel.setText("")
        self.pipelineLabel.setObjectName("pipelineLabel")
        self.Next_Button = QtWidgets.QPushButton(pipeline)
        self.Next_Button.setGeometry(QtCore.QRect(480, 710, 251, 51))
        self.Next_Button.setObjectName("Next_Button")

        # loading image
        self.pixmap = QPixmap("src\Pipeline.png")
 
        # adding image to label
        self.pipelineLabel.setPixmap(self.pixmap)

        self.retranslateUi(pipeline)
        QtCore.QMetaObject.connectSlotsByName(pipeline)


        self.Next_Button.clicked.connect(self.Next_Page)

    def retranslateUi(self, pipeline):
        _translate = QtCore.QCoreApplication.translate
        pipeline.setWindowTitle(_translate("pipeline", "pipeline_showcase"))
        self.Next_Button.setText(_translate("pipeline", "Next"))


    def Next_Page(self):

        # self.window=QtWidgets.QMainWindow()
        # self.ui=SplashScreen()      #------------->creating an object 
        # # self.ui.setupUi(self.window)
        # self.window.show()

        # pipeline.close()


        if Ui_pipeline.pipeline is not None:
            # Close the pipeline using the class attribute
            Ui_pipeline.pipeline.close()
        
        
        app.setStyleSheet('''
        #LabelTitle {
            font-size: 60px;
            color: #93deed;
        }

        #LabelDesc {
            font-size: 30px;
            color: #c2ced1;
        }

        #LabelLoading {
            font-size: 30px;
            color: #e8e8eb;
        }

        QFrame {
            background-color: #2F4454;
            color: rgb(220, 220, 220);
        }

        QProgressBar {
            background-color: #DA7B93;
            color: rgb(200, 200, 200);
            border-style: none;
            border-radius: 10px;
            text-align: center;
            font-size: 30px;
        }

        QProgressBar::chunk {
            border-radius: 10px;
            background-color: qlineargradient(spread:pad x1:0, x2:1, y1:0.511364, y2:0.523, stop:0 #1C3334, stop:1 #376E6F);
        }
    ''')


        self.splash = SplashScreen()
        self.splash.show()
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pipeline = QtWidgets.QDialog()
    ui = Ui_pipeline()
    ui.setupUi(pipeline)
    pipeline.show()
    
    sys.exit(app.exec_())
